{{- if .Values.ingress.enabled -}}
{{- $svcName := include "main.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "main.fullname" . }}-ingress
  labels:
    {{- include "main.labels" . | nindent 4 }}
  annotations:
    {{- include "ingress.annotations" . | nindent 4 }}
spec:
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
                service: 
                  {{- if and ($.Values.service.rootService.enabled) (empty .name) }}
                  name: {{ $svcName }}-root-svc
                  {{- else if .name }}
                  name: {{ $svcName }}-{{ .name }}-svc
                  {{- else }}
                  name: {{ $svcName }}-stable-svc
                  {{- end }} 
                  port:
                    {{- if .number }}
                    number: {{ .number }}
                    {{- else if empty .number }}
                    name: use-annotation
                    {{- end }}
          {{- end }}
    {{- end }}
{{- end }}