{{- $svcName := include "main.fullname" . -}}
{{- range (include "create.service" . | fromYaml).name -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $svcName }}-{{ . }}-svc
  labels:
    {{- include "main.labels" $ | nindent 4 }}
spec:
  type: {{ default "ClusterIP" $.Values.service.type }}
  ports:
    - name: {{ $svcName }}-{{ . }}-svc
      port: {{ $.Values.service.port }}
      targetPort: {{ include "main.port" $ }} # $ 사용 시 전체 변수에서 조회 가능
      protocol: {{ default "TCP" $.Values.service.protocol }}
  selector:
    {{- include "main.selectorLabels" $ | nindent 4 }}

{{ end }}