rollout-subchart-test: # Chart.yaml에 있는 name으로 작서 후 변수값을 들여쓰기
  title: "prod-rollout"
  app: echoserver
  env: prod

  rollout:
    type: canary
    replicas: 2
    image:
      repository: 932824558442.dkr.ecr.ap-northeast-2.amazonaws.com/nginx
      tag: 1.23-alpine
      digest: ""
      pullPolicy: IfNotPresent

    port:
      enabled: true
      containerport: 80

    resources: {}
      # limits:
      #   cpu: 100m
      #   memory: 128Mi
      # requests:
      #   cpu: 100m
      #   memory: 128Mi

    livenessProbe: {}
      # httpGet:
      #   path: /
      #   port: http

    readinessProbe: {}
      # httpGet:
      #   path: /
      #   port: http

    # maxSurge: "25%"
    # maxUnavailable: 0
    
    strategy: # {}
      - setWeight: 10
      - pause: { duration: 1m }
      - setWeight: 20
      - pause: { duration: 2m }
      - setWeight: 30
      - pause: { duration: 5m }
      - pause: {}

  service:
    port: 80
    protocol: TCP
    type: NodePort
    rootService:
      enabled: true

  ingress:
    enabled: true
    scheme: internet-facing #internet-facing or internal
    target_type: instance #select target-type 지정 (ip | instance(기본값))
    subnets: subnet-09f1ab2ff6e4f2988,subnet-0eccba1b1190cc500
    security_groups: sg-05e3d194ad1ebcd80

    hosts:
      - host: #chart-example.local
        paths:
          - path: /
            pathType: Prefix #Exact, Prefix
          - path: /test
            name: canary
            pathType: Exact
            number: 80